/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package napakalaki;

/**
 *
 * @author Mario
 */
public class JD_nombreJugadores extends javax.swing.JDialog {

    /**
     * Creates new form JD_nombreJugadores
     */
    public JD_nombreJugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugadores = new javax.swing.JPanel();
        jugador2Nombre = new javax.swing.JTextField();
        jugador4Nombre = new javax.swing.JTextField();
        jugador4 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        jugador3Nombre = new javax.swing.JTextField();
        jugador1Nombre = new javax.swing.JTextField();
        jugador1 = new javax.swing.JLabel();
        jugador3 = new javax.swing.JLabel();
        cuatroJugadores = new javax.swing.JCheckBox();
        comenzar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escriba el nombre de cada jugador");
        setResizable(false);

        jugadores.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jugador2Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jugador2Nombre.setText("Jugador 2");
        jugador2Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador2NombreActionPerformed(evt);
            }
        });

        jugador4Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jugador4Nombre.setText("Jugador 4");
        jugador4Nombre.setEnabled(false);

        jugador4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jugador4.setText("Jugador 4");
        jugador4.setEnabled(false);

        jugador2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jugador2.setText("Jugador 2");

        jugador3Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jugador3Nombre.setText("Jugador 3");
        jugador3Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador3NombreActionPerformed(evt);
            }
        });

        jugador1Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jugador1Nombre.setText("Jugador 1");
        jugador1Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1NombreActionPerformed(evt);
            }
        });

        jugador1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jugador1.setText("Jugador 1");

        jugador3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jugador3.setText("Jugador 3");

        javax.swing.GroupLayout jugadoresLayout = new javax.swing.GroupLayout(jugadores);
        jugadores.setLayout(jugadoresLayout);
        jugadoresLayout.setHorizontalGroup(
            jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugador3Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador4Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugador2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jugadoresLayout.setVerticalGroup(
            jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador1)
                    .addComponent(jugador1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugador2)
                    .addComponent(jugador2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador3)
                    .addComponent(jugador3Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugador4)
                    .addComponent(jugador4Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuatroJugadores.setText("Cuatro Jugadores");
        cuatroJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroJugadoresActionPerformed(evt);
            }
        });

        comenzar.setText("Comenzar");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cuatroJugadores)
                    .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuatroJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comenzar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugador1NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador1NombreActionPerformed

    private void jugador3NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador3NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador3NombreActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelarActionPerformed

    private void cuatroJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroJugadoresActionPerformed
        jugador4.setEnabled(cuatroJugadores.isSelected());
        jugador4Nombre.setEnabled(cuatroJugadores.isSelected());
    }//GEN-LAST:event_cuatroJugadoresActionPerformed

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        if(cuatroJugadores.isSelected()){
            nombres=new String[4];
            nombres[3]=jugador4Nombre.getText();
        }else nombres= new String[3];
        nombres[0]=jugador1Nombre.getText();
        nombres[1]=jugador2Nombre.getText();
        nombres[2]=jugador3Nombre.getText();
        this.dispose();
    }//GEN-LAST:event_comenzarActionPerformed

    private void jugador2NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador2NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador2NombreActionPerformed

        public String[] getNombres(){
        this.setVisible(true);
        return nombres;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton comenzar;
    private javax.swing.JCheckBox cuatroJugadores;
    private javax.swing.JLabel jugador1;
    private javax.swing.JTextField jugador1Nombre;
    private javax.swing.JLabel jugador2;
    private javax.swing.JTextField jugador2Nombre;
    private javax.swing.JLabel jugador3;
    private javax.swing.JTextField jugador3Nombre;
    private javax.swing.JLabel jugador4;
    private javax.swing.JTextField jugador4Nombre;
    private javax.swing.JPanel jugadores;
    // End of variables declaration//GEN-END:variables

    private String[] nombres;



}
